### ISSUE TITLE
Bug spell reflect su counterspell

### ISSUE THREAD

**Issue by pati3nc3** [AzerothShard/AzerothShard-Issues-ita#50]
la spell counterspell ( http://www.wowhead.com/spell=2139/counterspell) quando viene effettuata sul war dovrebbe levare il reflect senza causare altre meccaniche invece sul nuovo core al cast del cs su reflect il cs silenzia il mage.

**Comment by mik1893** [comment]
falso - in wotlk reflecta eccome.
Non reflecta mettendo i punti talento in IMPROVED COUNTER SPELL, ma comunque NON si mangia il reflect del warrior, e' assolutamente falso (e lo so per esperienza avendo giocato wotlk su offy, in questo caso).
Basta googlare e infatti dice esattamente questo, praticamente ovunque si guardi.

http://www.arenajunkies.com/topic/128917-mage-spell-reflect-tips-3/ 

_Lol, I was trolling with the counterspell :P
I was serious though haha.. Wouldn't counterspell eat up the spell reflect?_ 

_Humanclass_name
US-Emerald Dream
Shadowburn
Posts: 1459
LocationON, Canada
Posted 24 February 2010 - 09:37 PM
If you like silencing yourself feel free to do that._ 

http://wiki.eternal-wow.com/index.php/Frost_Mage_(Wrath_of_the_Lich_King) 

- Counter Spell – This skill is not only to interrupt casting. With the talent of Improved Counter Spell it should also be used to prevent people with a lot of instant casts to do something at 
crucial moments. It should also be used against Death Knights, because of the amount of skills that they use. Counter Spell is also a great skill if you are fighting against Warriors in a 
1 versus 1. Since the talent of Improved Counter Spell does not reflect, you will not get silenced if the Warrior Spell Reflects it, this means that you can waste there Spell Reflect 
without receiving any damage or activating global cooldown.
